In [1]:
import numpy as np
print(np.__version__)
a = np.array([1,2,3])



2.1.3


In [2]:
assert(a.dtype == np.int64)


In [5]:
assert(a.shape == (3,) )

In [6]:
assert(isinstance(a.shape,tuple))

In [7]:
a = np.zeros(4)
assert a == [0,0,0,0]  # this gives error

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [9]:
ab = [1,2,3]

In [10]:
ab == [1,2,3]

True

In [11]:
all([True,False])

False

In [12]:
any([False,False])

False

In [13]:
a = np.array([0.12,0.45,0.78,1.34,2.91])
assert(a.shape == (5,))

In [14]:
[x for x in range(1,25)]

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24]

In [15]:
a = np.array(np.arange(1,25,1,np.int8))

In [16]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int8)

In [17]:
b = a.reshape(2,12)

In [18]:
b

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]], dtype=int8)

In [19]:
c = a.reshape(3,8)

In [20]:
c


array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int8)

In [21]:
v = np.array([1.5, 2.0, 3.0])

In [23]:
W = np.array([
    [0.2,  0.8],
    [-0.5, 0.1],
    [0.8, -0.3]
])


b = np.array([0.5, -0.2])

# Activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))
z = np.dot(v, W) + b

# 2. Apply activation
a = sigmoid(z)

print("Hidden layer activations:", a)

Hidden layer activations: [0.90024951 0.57444252]
