In [ ]:
import numpy as np


In [ ]:
mylist = [1,2,3]    #converting list to array
n = np.array(mylist)

In [ ]:
n

array([1, 2, 3])

In [ ]:
m = np.array([[1,2,3],[4,5,6]])

In [ ]:
m.shape

(2, 3)

In [ ]:
n = np.arange(0,30,2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [ ]:
n.reshape(3,5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [ ]:
lspace = np.linspace(0,10,9)
lspace

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [ ]:
lspace.resize(3,3)
lspace

array([[ 0.  ,  1.25,  2.5 ],
       [ 3.75,  5.  ,  6.25],
       [ 7.5 ,  8.75, 10.  ]])

In [ ]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.eye(4) #eigen

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
num = np.matrix([[1,2,3],
                [4,5,6],
                [7,8,9] ])
num

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
type(num)

numpy.matrix

In [ ]:
print("Main Diagonal elements:\n",np.diag(num))
print("\nDiagonal elements above main diagonal:\n", np.diag(num,1))
print("\nDiagonal elements below main diagonal:\n", np.diag(num,-1))
print("\nDiagonal elements above up 2 diagonal:\n", np.diag(num,2))

Main Diagonal elements:
 [1 5 9]

Diagonal elements above main diagonal:
 [2 6]

Diagonal elements below main diagonal:
 [4 8]

Diagonal elements above up 2 diagonal:
 [3]


In [ ]:
np.array([1,2,3]*3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [ ]:
np.repeat([1,2,3],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [ ]:
p = np.ones([3,3],int)
p

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
np.vstack([p,2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [ ]:
np.hstack([p,2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

In [ ]:
x = np.array([1,2,3])
y = np.array([4,5,6])
print(x+y)
print(x-y)
print(x*y) #element wise multiplication

print(x/y)
print(x**y)
print(x@y) #matrix multiplication
print(x**2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]
32
[1 4 9]


In [ ]:
x.dot(y)

np.int64(32)

In [ ]:
z = np.matrix([[1,2,3],
                [4,5,6],
                [7,8,9] ])

In [ ]:
z.T

matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [ ]:
z.dtype

dtype('int64')

In [ ]:
z.astype('f')

matrix([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]], dtype=float32)

In [ ]:
a = np.array([-4,-2,1,3,5])
a.sum()

np.int64(3)

In [ ]:
a.max()


np.int64(5)

In [ ]:
a.min()

np.int64(-4)

In [ ]:
a.mean()


np.float64(0.6)

In [ ]:
a.std()

np.float64(3.2619012860600183)

In [ ]:
a.argmax()

np.int64(4)

In [ ]:
a.argmin()

np.int64(0)

In [ ]:
s = np.arange(100)

In [ ]:
s

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
s.reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
s = np.arange(6)**2

In [ ]:
s

array([ 0,  1,  4,  9, 16, 25])

In [ ]:
s[0], s[4], s[-1]

(np.int64(0), np.int64(16), np.int64(25))

In [ ]:
s[1:5]

array([ 1,  4,  9, 16])

In [ ]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [ ]:
s[-4:]

array([ 81, 100, 121, 144])

In [ ]:
s[-5::-2]

array([64, 36, 16,  4,  0])

In [ ]:
s[-5:-2]

array([ 64,  81, 100])

In [ ]:
r = np.arange(100)
r.resize(10,10)


In [ ]:
r[3,4]

np.int64(34)

In [ ]:
r[2,1:4]

array([21, 22, 23])

In [ ]:
r[3,3:6]

array([33, 34, 35])

In [ ]:
r[:3, :-1]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [20, 21, 22, 23, 24, 25, 26, 27, 28]])

In [ ]:
r

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
r[-1,::2]

array([90, 92, 94, 96, 98])

In [ ]:
r[r>30]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
       65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
       82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98,
       99])

In [ ]:
r[r>30] =30

In [ ]:
r

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30]])

In [ ]:
r2 = r[:3,:3]
r2

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [ ]:
r2[:] = 0

In [ ]:
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
r

array([[ 0,  0,  0,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  0,  0, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  0,  0, 23, 24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30]])

In [ ]:
r_copy = r.copy()
r_copy[:] = 10


In [ ]:
r_copy

array([[10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]])

In [ ]:
test = np.random.randint(0,10,(4,3))

In [ ]:
test2 = test**2

In [ ]:
test2

array([[25,  9,  4],
       [49, 25, 49],
       [36,  1, 81],
       [16, 64, 49]])

In [ ]:
for i, row in enumerate(test):
  print('row', i, 'is', row)

row 0 is [5 3 2]
row 1 is [7 5 7]
row 2 is [6 1 9]
row 3 is [4 8 7]


In [ ]:
for i,j in zip(test,test2):
  print(i,'+',j,'=', i + j)

[5 3 2] + [25  9  4] = [30 12  6]
[7 5 7] + [49 25 49] = [56 30 56]
[6 1 9] + [36  1 81] = [42  2 90]
[4 8 7] + [16 64 49] = [20 72 56]


In [ ]:
marks  = np.array([[80,75,90],
                  [50,45,33],
                  [33,54,88],
                  [34,65,22]
]
                  )

In [ ]:
student_total = np.sum(marks,axis = 1)

In [ ]:
student_total

array([245, 128, 175, 121])

## Practice Session


In [ ]:
# Create a constant array
		# Prints "[[ 7.  7.]
    #         [ 7.  7.]]"
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [ ]:
 # Create an array filled with random values
         # Might print "[[ 0.91940167  0.08143941]
         #               [ 0.68744134  0.87236687]]"

np.random(2,2)

TypeError: 'module' object is not callable

In [ ]:

rng = np.random.default_rng()  #generates random number

In [ ]:
a = rng.random((2,2))

In [ ]:
a

array([[0.56221692, 0.83791633],
       [0.52962764, 0.71138664]])

In [ ]:
#Create a NumPy array containing the numbers from 10 to 50. Display:

#The array
#Number of elements
#Shape
#Dimension
#Data type

In [ ]:
x = np.arange(10,51)

In [ ]:
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [ ]:
x.size

41

In [ ]:
x.ndim

1

In [ ]:
x.dtype

dtype('int64')

In [ ]:
 '''Using NumPy, create:

A 1D array containing 10 zeros
A 3 × 3 array containing ones
A 4 × 4 identity matrix
An array containing numbers from 5 to 50 with a step size of 5.'''

'Using NumPy, create:\n\nA 1D array containing 10 zeros\nA 3 × 3 array containing ones\nA 4 × 4 identity matrix\nAn array containing numbers from 5 to 50 with a step size of 5.'

In [ ]:
y = np.zeros(10)

In [ ]:
y

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
z = np.ones((3,3))

In [ ]:
z

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.eye((4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.arange(5,51,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [ ]:
''' Create an array containing numbers from 1 to 24. Reshape it into:

4 × 6
6 × 4
2 × 3 × 4'''


In [ ]:
a = np.arange(1,25)

In [ ]:
a.reshape(4,6)
a.ndim

1

In [ ]:
a.reshape(6,4)
a.ndim

1

In [ ]:
a.reshape(2,3,4)
a.ndim

1

In [ ]:
marks = np.array([78, 85, 92, 67, 88, 73, 95, 81])